#!/bin/bash

# Check for the two binaries that may not be shipped with the LFS system
if [[ ! -e /bin/lynx ]]; then
    echo "lynx binary not found"
    exit -1
fi
if [[ ! -e /bin/wget ]]; then
    echo "wget binary not found"
    exit -1
fi

if [[ -f /advisories/current_adv ]]; then
    echo "Previous security advisory list was found; Downloading and comparing."
    mv /advisories/current_adv /advisories/old_adv
    wget -q https://linuxfromscratch.org/lfs/advisories/12.3.html -O /advisories/current_adv
    out=$(diff /advisories/old_adv /advisories/current_adv)
    if [[ "$out" == "$(echo)" ]]; then
        echo "<h1>New security advisories:</h1></br>$out" | lynx -stdin
    else
        echo "No new security advisories."
    fi
else
    echo "No previous security advisory list found; Showing all (if any)"
    wget -q https://linuxfromscratch.org/lfs/advisories/12.3.html -O /advisories/current_adv
    cat /advisories/current_adv | lynx -stdin
fi
